# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30e26506a088ccbf0dc00fc17a219300f6f3fd65f82bcb94686d2f7ab68a50caf1f81ef7714a15c8ac3d1fb3b61286e418b8094c1e13611b8f14c9e8781c12a3

test:
  secret_key_base: 00d7ad57c0792ab81c06b04a82b86e76b5b93c427a0cbf64c58165697e2af519be7388c1a3e1bea6bac1178f066f4b763baec4a402d94f0647c31eff0216776d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
